// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avsc
 */
package dtsavro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum int

const (
	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumField UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 0

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumInteger UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 1

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumCharacter UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 2

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumFloat UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 3

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDecimal UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 4

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestamp UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 5

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDateTime UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 6

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestampWithTimeZone UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 7

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryGeometry UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 8

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextGeometry UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 9

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryObject UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 10

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextObject UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 11

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumEmptyObject UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 12

	UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumRecord UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 13
)

type UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord struct {
	Field                 *Field
	Integer               *Integer
	Character             *Character
	Float                 *Float
	Decimal               *Decimal
	Timestamp             *Timestamp
	DateTime              *DateTime
	TimestampWithTimeZone *TimestampWithTimeZone
	BinaryGeometry        *BinaryGeometry
	TextGeometry          *TextGeometry
	BinaryObject          *BinaryObject
	TextObject            *TextObject
	EmptyObject           EmptyObject
	Record                *Record
	UnionType             UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum
}

func writeUnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord(r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord, w io.Writer) error {

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumField:
		return writeField(r.Field, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumInteger:
		return writeInteger(r.Integer, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumCharacter:
		return writeCharacter(r.Character, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumFloat:
		return writeFloat(r.Float, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDecimal:
		return writeDecimal(r.Decimal, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestamp:
		return writeTimestamp(r.Timestamp, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDateTime:
		return writeDateTime(r.DateTime, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestampWithTimeZone:
		return writeTimestampWithTimeZone(r.TimestampWithTimeZone, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryGeometry:
		return writeBinaryGeometry(r.BinaryGeometry, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextGeometry:
		return writeTextGeometry(r.TextGeometry, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryObject:
		return writeBinaryObject(r.BinaryObject, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextObject:
		return writeTextObject(r.TextObject, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumEmptyObject:
		return writeEmptyObject(r.EmptyObject, w)
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumRecord:
		return writeRecord(r.Record, w)
	}
	return fmt.Errorf("invalid value for *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord")
}

func NewUnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord() *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord {
	return &UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord{}
}

func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetString(v string) {
	panic("Unsupported operation")
}
func (r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetLong(v int64) {
	r.UnionType = (UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum)(v)
}
func (r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) Get(i int) types.Field {
	switch i {
	case 0:
		r.Field = NewField()
		return r.Field
	case 1:
		r.Integer = NewInteger()
		return r.Integer
	case 2:
		r.Character = NewCharacter()
		return r.Character
	case 3:
		r.Float = NewFloat()
		return r.Float
	case 4:
		r.Decimal = NewDecimal()
		return r.Decimal
	case 5:
		r.Timestamp = NewTimestamp()
		return r.Timestamp
	case 6:
		r.DateTime = NewDateTime()
		return r.DateTime
	case 7:
		r.TimestampWithTimeZone = NewTimestampWithTimeZone()
		return r.TimestampWithTimeZone
	case 8:
		r.BinaryGeometry = NewBinaryGeometry()
		return r.BinaryGeometry
	case 9:
		r.TextGeometry = NewTextGeometry()
		return r.TextGeometry
	case 10:
		r.BinaryObject = NewBinaryObject()
		return r.BinaryObject
	case 11:
		r.TextObject = NewTextObject()
		return r.TextObject
	case 12:
		return &EmptyObjectWrapper{Target: (&r.EmptyObject)}
	case 13:
		r.Record = NewRecord()
		return r.Record
	}
	panic("Unknown field index")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) NullField(i int) {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) Finalize() {
}

func (r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumField:
		return json.Marshal(map[string]interface{}{"Field": r.Field})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumInteger:
		return json.Marshal(map[string]interface{}{"Integer": r.Integer})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumCharacter:
		return json.Marshal(map[string]interface{}{"Character": r.Character})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumFloat:
		return json.Marshal(map[string]interface{}{"Float": r.Float})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDecimal:
		return json.Marshal(map[string]interface{}{"Decimal": r.Decimal})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestamp:
		return json.Marshal(map[string]interface{}{"Timestamp": r.Timestamp})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDateTime:
		return json.Marshal(map[string]interface{}{"DateTime": r.DateTime})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestampWithTimeZone:
		return json.Marshal(map[string]interface{}{"TimestampWithTimeZone": r.TimestampWithTimeZone})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryGeometry:
		return json.Marshal(map[string]interface{}{"BinaryGeometry": r.BinaryGeometry})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextGeometry:
		return json.Marshal(map[string]interface{}{"TextGeometry": r.TextGeometry})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryObject:
		return json.Marshal(map[string]interface{}{"BinaryObject": r.BinaryObject})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextObject:
		return json.Marshal(map[string]interface{}{"TextObject": r.TextObject})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumEmptyObject:
		return json.Marshal(map[string]interface{}{"EmptyObject": r.EmptyObject})
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumRecord:
		return json.Marshal(map[string]interface{}{"Record": r.Record})
	}
	return nil, fmt.Errorf("invalid value for *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord")
}

func (r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["Field"]; ok {
		r.UnionType = 0
		return json.Unmarshal([]byte(value), &r.Field)
	}
	if value, ok := fields["Integer"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Integer)
	}
	if value, ok := fields["Character"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.Character)
	}
	if value, ok := fields["Float"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.Float)
	}
	if value, ok := fields["Decimal"]; ok {
		r.UnionType = 4
		return json.Unmarshal([]byte(value), &r.Decimal)
	}
	if value, ok := fields["Timestamp"]; ok {
		r.UnionType = 5
		return json.Unmarshal([]byte(value), &r.Timestamp)
	}
	if value, ok := fields["DateTime"]; ok {
		r.UnionType = 6
		return json.Unmarshal([]byte(value), &r.DateTime)
	}
	if value, ok := fields["TimestampWithTimeZone"]; ok {
		r.UnionType = 7
		return json.Unmarshal([]byte(value), &r.TimestampWithTimeZone)
	}
	if value, ok := fields["BinaryGeometry"]; ok {
		r.UnionType = 8
		return json.Unmarshal([]byte(value), &r.BinaryGeometry)
	}
	if value, ok := fields["TextGeometry"]; ok {
		r.UnionType = 9
		return json.Unmarshal([]byte(value), &r.TextGeometry)
	}
	if value, ok := fields["BinaryObject"]; ok {
		r.UnionType = 10
		return json.Unmarshal([]byte(value), &r.BinaryObject)
	}
	if value, ok := fields["TextObject"]; ok {
		r.UnionType = 11
		return json.Unmarshal([]byte(value), &r.TextObject)
	}
	if value, ok := fields["EmptyObject"]; ok {
		r.UnionType = 12
		return json.Unmarshal([]byte(value), &r.EmptyObject)
	}
	if value, ok := fields["Record"]; ok {
		r.UnionType = 13
		return json.Unmarshal([]byte(value), &r.Record)
	}
	return fmt.Errorf("invalid value for *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord")
}
